import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

const NAMES=["Minka","Luna","Mochi","Nala","Simba","Pixel","Flocke","Keks","Milo","Tapsi","Nova","Chili","Suki","Pünktchen","Momo","Zora"];
const COLORS=["orange","black","white","gray","cream","calico"];
const PATTERNS=["solid","tabby","tuxedo","spots","marble","lynx"];
const RARITIES=["Gewöhnlich","Selten","Episch","Legendär","Mythisch"];
const ACTIVITIES={idle:"Schaut sich um",walk:"Streift durch das Zimmer",eat:"Frisst genüsslich",play:"Jagt dem Garn nach",sleep:"Schläft tief",pet:"Schnurrt glücklich"};
const baseCat=(id,name,sex,color,pattern="tabby")=>({id,name,sex,color,pattern,rarity:0,age:2.2,growth:25,happiness:82,hunger:82,health:100,size:1,genes:{size:2,beauty:2,energy:2,luck:1,temper:2},parents:[],generation:1,cooldown:0,wins:0,activity:"idle"});
const empty={coins:350,food:140,toys:15,science:0,hearts:35,lineage:0,reputation:0,selected:1,nextId:3,last:Date.now(),buildings:{kitchen:0,nursery:1,lab:0,playroom:0,garden:0,showhall:0},research:{growth:0,fertility:0,genes:0,offline:0,gestation:0,training:0},cats:[baseCat(1,"Minka","♀","orange"),baseCat(2,"Milo","♂","gray","solid")],quests:{feed:0,pet:0,breed:0,show:0},nest:null,visitors:[],codex:["orange-tabby","gray-solid"],selectedA:1,selectedB:2,showLog:[]};
const load=()=>{try{return{...structuredClone(empty),...JSON.parse(localStorage.getItem("kitty-breeder-v3")||"{}")}}catch{return structuredClone(empty)}};
const fmt=n=>n>=1e6?(n/1e6).toFixed(1)+"M":n>=1e3?(n/1e3).toFixed(1)+"K":Math.floor(n);
const pick=a=>a[Math.floor(Math.random()*a.length)];
const stage=c=>c.age<1?"Kätzchen":c.age<3?"Jungkatze":c.age<10?"Erwachsen":c.age<15?"Senior":"Uralte Katze";
const stageClass=c=>c.age<1?"baby":c.age<3?"young":c.age<10?"adult":c.age<15?"senior":"ancient";
const geneScore=c=>Object.values(c.genes).reduce((a,b)=>a+b,0);
const value=c=>Math.floor(geneScore(c)*42*(1+c.rarity*.75)*(1+c.generation*.18)+c.wins*120);
const keyOf=c=>`${c.color}-${c.pattern}`;

const PALETTES={orange:["#d78943","#f0ad62","#6d3b2b"],black:["#25222d","#45404f","#111019"],white:["#ddd8cf","#fffaf0","#77717b"],gray:["#696a73","#96969d","#34343c"],cream:["#d7ba83","#f0d6a3","#70563e"],calico:["#c47a46","#eee0c8","#332b32"]};
function PixelCat({cat,mini=false,className=""}){
 const p=PALETTES[cat.color]||PALETTES.orange;
 const stageName=stageClass(cat);
 return <svg className={`pixel-svg-cat ${mini?"mini-svg-cat":""} ${stageName} activity-${cat.activity||"idle"} ${className}`} viewBox="0 0 32 32" role="img" aria-label={`${cat.name||"Katze"} Pixelkatze`} shapeRendering="crispEdges">
  <g className="cat-whole">
   <g className="cat-tail"><rect x="3" y="17" width="3" height="8" fill={p[2]}/><rect x="5" y="13" width="3" height="5" fill={p[0]}/><rect x="7" y="11" width="3" height="4" fill={p[1]}/></g>
   <g className="cat-body"><rect x="8" y="15" width="15" height="11" fill={p[0]}/><rect x="10" y="13" width="11" height="3" fill={p[1]}/><rect x="9" y="24" width="4" height="5" fill={p[2]}/><rect x="18" y="24" width="4" height="5" fill={p[2]}/></g>
   <g className="cat-head"><rect x="16" y="7" width="12" height="13" fill={p[0]}/><rect x="17" y="4" width="4" height="5" fill={p[2]}/><rect x="24" y="4" width="4" height="5" fill={p[2]}/><rect x="18" y="9" width="8" height="8" fill={p[1]}/><rect x="19" y="11" width="2" height="2" fill="#17131d"/><rect x="24" y="11" width="2" height="2" fill="#17131d"/><rect x="22" y="14" width="2" height="2" fill="#d98a91"/><rect className="cat-mouth" x="21" y="16" width="4" height="1" fill="#4b2730"/></g>
   {cat.pattern!=="solid"&&<g className="cat-pattern" fill={p[2]} opacity=".9"><rect x="12" y="15" width="2" height="6"/><rect x="16" y="15" width="2" height="5"/>{cat.pattern==="spots"&&<rect x="19" y="20" width="3" height="3"/>}{cat.pattern==="tuxedo"&&<rect x="20" y="15" width="4" height="7" fill="#f4eee6"/>}</g>}
  </g>
 </svg>
}

function App(){
 const[s,setS]=useState(load),[tab,setTab]=useState("cats"),[note,setNote]=useState("");
 const cat=s.cats.find(c=>c.id===s.selected)||s.cats[0];
 const production=useMemo(()=>{const mood=s.cats.reduce((a,c)=>a+(c.happiness+c.health)/200,0);return{coins:(s.buildings.playroom*1.5+s.buildings.garden*.8+s.cats.length*.22)*mood*(1+s.lineage*.12),food:s.buildings.kitchen*.4,science:s.buildings.lab*.09,reputation:s.buildings.showhall*.018}},[s.cats,s.buildings,s.lineage]);
 const toast=t=>{setNote(t);clearTimeout(window.kt);window.kt=setTimeout(()=>setNote(""),1900)};
 const mutate=fn=>setS(p=>{const n=structuredClone(p);fn(n);return n});
 const setActivity=(id,a,ms=2400)=>{mutate(n=>{const c=n.cats.find(x=>x.id===id);if(c)c.activity=a});setTimeout(()=>mutate(n=>{const c=n.cats.find(x=>x.id===id);if(c&&c.activity===a)c.activity="idle"}),ms)};
 const act=type=>{const id=s.selected;mutate(n=>{const c=n.cats.find(x=>x.id===id);if(!c)return;if(type==="feed"){if(n.food<5)return toast("Nicht genug Futter");n.food-=5;c.hunger=Math.min(100,c.hunger+27);c.growth+=8+n.research.growth*2;n.quests.feed++}if(type==="pet"){c.happiness=Math.min(100,c.happiness+16);c.health=Math.min(100,c.health+2);n.hearts+=1+c.rarity;n.quests.pet++}if(type==="play"){if(n.toys<1)return toast("Keine Spielzeuge");n.toys--;c.happiness=Math.min(100,c.happiness+24);c.hunger=Math.max(0,c.hunger-5);c.growth+=5;c.genes.energy+=Math.random()<.035?1:0}if(type==="sleep"){c.health=Math.min(100,c.health+9);c.happiness=Math.min(100,c.happiness+5);c.hunger=Math.max(0,c.hunger-2)}if(c.growth>=100){c.growth-=100;c.size+=.1+c.genes.size*.025;n.coins+=Math.floor(45*c.size);toast(`${c.name} ist sichtbar gewachsen!`)}});setActivity(id,type==="feed"?"eat":type,type==="sleep"?5000:2600)};
 const buy=kind=>mutate(n=>{const lv=n.buildings[kind],base={kitchen:120,nursery:230,lab:420,playroom:180,garden:310,showhall:600}[kind],cost=Math.floor(base*1.75**lv);if(n.coins<cost)return toast("Nicht genug Münzen");n.coins-=cost;n.buildings[kind]++;toast("Gebäude verbessert")});
 const study=kind=>mutate(n=>{const lv=n.research[kind],cost=Math.floor(25*2.05**lv);if(n.science<cost)return toast("Nicht genug Forschung");n.science-=cost;n.research[kind]++;toast("Forschung abgeschlossen")});
 const startBreed=()=>mutate(n=>{if(n.nest)return toast("Das Nest ist bereits belegt");const a=n.cats.find(c=>c.id===n.selectedA),b=n.cats.find(c=>c.id===n.selectedB);if(!a||!b||a.id===b.id)return toast("Wähle zwei verschiedene Katzen");if(a.sex===b.sex)return toast("Für diese Zucht brauchst du ♀ und ♂");if(a.age<2||b.age<2)return toast("Beide Katzen müssen erwachsen sein");if(a.cooldown>0||b.cooldown>0)return toast("Eine Katze hat noch Zuchtpause");if(n.hearts<20)return toast("Du brauchst 20 Herzen");if(n.cats.length>=4+n.buildings.nursery*2)return toast("Kinderstube voll");n.hearts-=20;const duration=Math.max(18,45-n.research.gestation*5);n.nest={a:a.id,b:b.id,remaining:duration,total:duration,eggs:1+(Math.random()<.22+n.research.fertility*.04?1:0)};a.cooldown=90;b.cooldown=90;toast("Zucht gestartet – das Nest wird vorbereitet")});
 const hatch=()=>mutate(n=>{if(!n.nest||n.nest.remaining>0)return;const a=n.cats.find(c=>c.id===n.nest.a),b=n.cats.find(c=>c.id===n.nest.b);const babies=[];for(let i=0;i<n.nest.eggs;i++){const gene=k=>Math.max(1,Math.round((a.genes[k]+b.genes[k])/2)+(Math.random()<.08+n.research.genes*.03?1:0));const pattern=Math.random()<.72?pick([a.pattern,b.pattern]):pick(PATTERNS);const color=Math.random()<.72?pick([a.color,b.color]):pick(COLORS);const rarity=Math.min(4,Math.max(a.rarity,b.rarity)+(Math.random()<.07+n.research.fertility*.018?1:0));const baby={id:n.nextId++,name:pick(NAMES),sex:Math.random()<.5?"♀":"♂",color,pattern,rarity,age:0,growth:0,happiness:95,hunger:92,health:100,size:.62,genes:{size:gene("size"),beauty:gene("beauty"),energy:gene("energy"),luck:gene("luck"),temper:gene("temper")},parents:[a.name,b.name],generation:Math.max(a.generation,b.generation)+1,cooldown:0,wins:0,activity:"sleep"};babies.push(baby);if(!n.codex.includes(keyOf(baby)))n.codex.push(keyOf(baby))}n.cats.push(...babies);n.selected=babies[0].id;n.nest=null;n.quests.breed++;toast(`${babies.length} Kätzchen geschlüpft!`)});
 const enterShow=()=>mutate(n=>{const c=n.cats.find(x=>x.id===n.selected);if(c.age<2)return toast("Nur erwachsene Katzen dürfen antreten");if(n.coins<50)return toast("50 Münzen Startgebühr benötigt");n.coins-=50;const score=geneScore(c)*10+c.happiness*.4+c.health*.4+c.rarity*40+c.genes.luck*Math.random()*18+n.research.training*12;const rival=115+n.reputation*1.2+Math.random()*120;const win=score>rival;if(win){const prize=Math.floor(120+score*.8);n.coins+=prize;n.reputation+=3+c.rarity;c.wins++;n.quests.show++;toast(`${c.name} gewinnt ${prize} Münzen!`)}else{n.reputation+=.5;toast(`${c.name} sammelt wertvolle Erfahrung`)}n.showLog.unshift({name:c.name,win,score:Math.floor(score)});n.showLog=n.showLog.slice(0,5);setActivity(c.id,"walk",3500)});
 const attract=()=>mutate(n=>{if(n.food<15)return toast("15 Futter benötigt");n.food-=15;const color=pick(COLORS),pattern=pick(PATTERNS),rare=Math.random()<.16+Math.min(.2,n.buildings.garden*.025);const visitor={id:Date.now(),name:pick(NAMES),color,pattern,rarity:rare?1+Math.floor(Math.random()*3):0,stay:60};n.visitors.push(visitor);toast(`${visitor.name} besucht deinen Garten!`)});
 const adoptVisitor=id=>mutate(n=>{const v=n.visitors.find(x=>x.id===id);if(!v)return;const cost=150*(v.rarity+1);if(n.coins<cost)return toast(`${cost} Münzen benötigt`);if(n.cats.length>=4+n.buildings.nursery*2)return toast("Kinderstube voll");n.coins-=cost;const c=baseCat(n.nextId++,v.name,Math.random()<.5?"♀":"♂",v.color,v.pattern);c.rarity=v.rarity;c.genes={size:1+Math.ceil(Math.random()*3),beauty:1+v.rarity+Math.ceil(Math.random()*2),energy:1+Math.ceil(Math.random()*3),luck:1+v.rarity,temper:1+Math.ceil(Math.random()*3)};n.cats.push(c);n.visitors=n.visitors.filter(x=>x.id!==id);if(!n.codex.includes(keyOf(c)))n.codex.push(keyOf(c));toast(`${c.name} gehört jetzt zu deinem Hof`)});
 const sell=()=>mutate(n=>{if(n.cats.length<=2)return toast("Zwei Katzen müssen bleiben");const c=n.cats.find(x=>x.id===n.selected);const price=value(c);n.coins+=price;n.cats=n.cats.filter(x=>x.id!==c.id);n.selected=n.cats[0].id;toast(`Vermittelt für ${price} Münzen`)});
 const prestige=()=>mutate(n=>{if(n.reputation<80||n.cats.length<8)return toast("Benötigt 8 Katzen und 80 Ruf");const gain=Math.max(1,Math.floor((n.reputation+n.cats.reduce((a,c)=>a+c.generation*3+c.rarity*5,0))/70));const fresh=structuredClone(empty);fresh.lineage=n.lineage+gain;fresh.coins=350+gain*140;Object.assign(n,fresh);toast(`Neue Blutlinie: +${gain} Siegel`)});
 useEffect(()=>{const offline=Math.min(43200,(Date.now()-(s.last||Date.now()))/1000)*(1+s.research.offline*.25);if(offline>30)mutate(n=>{n.coins+=production.coins*offline;n.food+=production.food*offline;n.science+=production.science*offline;toast(`Offline: +${fmt(production.coins*offline)} Münzen`)});const t=setInterval(()=>mutate(n=>{n.coins+=production.coins;n.food+=production.food;n.science+=production.science;n.reputation+=production.reputation;n.last=Date.now();if(n.nest)n.nest.remaining=Math.max(0,n.nest.remaining-1);n.visitors.forEach(v=>v.stay--);n.visitors=n.visitors.filter(v=>v.stay>0);n.cats.forEach(c=>{c.age+=1/900;c.cooldown=Math.max(0,c.cooldown-1);c.hunger=Math.max(0,c.hunger-.035);c.happiness=Math.max(0,c.happiness-.018);if(c.hunger<20)c.health=Math.max(0,c.health-.04);else c.health=Math.min(100,c.health+.012);if(c.activity==="idle"&&Math.random()<.018)c.activity=pick(["walk","sleep","idle"])})}),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>localStorage.setItem("kitty-breeder-v3",JSON.stringify({...s,last:Date.now()})),[s]);
 const adultOptions=s.cats.filter(c=>c.age>=2);
 return <main className="app"><div className={`toast ${note?"show":""}`}>{note}</div><header>{[["Münzen","🪙",fmt(s.coins)],["Futter","🥣",fmt(s.food)],["Herzen","💗",fmt(s.hearts)],["Ruf","🏆",fmt(s.reputation)],["Blutlinie","🧬",s.lineage]].map(x=><div key={x[0]}><small>{x[0]}</small>{x[1]} {x[2]}</div>)}</header>
 <nav>{[["cats","Hof"],["breed","Zucht"],["garden","Garten"],["show","Shows"],["home","Ausbau"],["research","Forschung"],["codex","Katzenbuch"]].map(([k,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav>
 {tab==="cats"&&<><section className="card hero"><div className="title"><div><h1>{cat.name} <span>{cat.sex}</span></h1><p>{RARITIES[cat.rarity]} · Gen. {cat.generation} · {stage(cat)}</p></div><b className={`rarity r${cat.rarity}`}>{"★".repeat(cat.rarity+1)}</b></div><div className={`scene scene-${cat.activity}`}><div className="pixel-room"/><div className="food-bowl"/><div className="yarn-ball"/><PixelCat cat={cat}/><div className="activity-bubble">{ACTIVITIES[cat.activity]}</div><span className="age">{cat.age.toFixed(1)} Jahre · {cat.size.toFixed(2)}× · Pause {Math.ceil(cat.cooldown)}s</span></div><Bars cat={cat}/><div className="actions"><button onClick={()=>act("feed")}>🥣 Füttern</button><button onClick={()=>act("pet")}>💗 Kuscheln</button><button onClick={()=>act("play")}>🧶 Spielen</button><button onClick={()=>act("sleep")}>🌙 Schlafen</button><button onClick={enterShow}>🏆 Show</button><button className="danger" onClick={sell}>🏠 Vermitteln</button></div></section><section className="card"><h2>Deine Katzen <small>{s.cats.length}/{4+s.buildings.nursery*2}</small></h2><div className="catgrid">{s.cats.map(c=><button key={c.id} className={`catcard ${c.id===s.selected?"selected":""}`} onClick={()=>setS(p=>({...p,selected:c.id}))}><PixelCat cat={c} mini/><b>{c.name}</b><small>Gen. {c.generation} · {RARITIES[c.rarity]}</small><small>{c.activity!=="idle"?ACTIVITIES[c.activity]:`${c.wins} Siege`}</small></button>)}</div></section></>}
 {tab==="breed"&&<section className="card"><h1>Zuchtzentrum</h1><p>Wähle zwei erwachsene Katzen. Fell, Muster, Temperament und Gene werden sichtbar vererbt; seltene Mutationen können neue Linien erzeugen.</p><div className="parent-pickers"><label>Mutter<select value={s.selectedA} onChange={e=>setS(p=>({...p,selectedA:+e.target.value}))}>{adultOptions.map(c=><option key={c.id} value={c.id}>{c.name} {c.sex} · G{c.generation}</option>)}</select></label><label>Vater<select value={s.selectedB} onChange={e=>setS(p=>({...p,selectedB:+e.target.value}))}>{adultOptions.map(c=><option key={c.id} value={c.id}>{c.name} {c.sex} · G{c.generation}</option>)}</select></label></div>{s.nest?<div className="nest"><div className="nest-eggs">{"🥚".repeat(s.nest.eggs)}</div><b>{s.nest.remaining>0?`Schlüpft in ${Math.ceil(s.nest.remaining)} Sekunden`:"Die Kätzchen sind bereit!"}</b><div className="progress"><i style={{width:`${100-s.nest.remaining/s.nest.total*100}%`}}/></div><button className="big" disabled={s.nest.remaining>0} onClick={hatch}>🐾 Kätzchen schlüpfen lassen</button></div>:<button className="big" onClick={startBreed}>💞 Zucht beginnen · 20 Herzen</button>}<h2>Gene der ausgewählten Katze</h2><div className="gene-panel">{Object.entries(cat.genes).map(([k,v])=><div key={k}><span>{{size:"Größe",beauty:"Schönheit",energy:"Energie",luck:"Glück",temper:"Temperament"}[k]}</span><b>{v}</b></div>)}</div><button className="prestige" onClick={prestige}>🧬 Neue Blutlinie beginnen</button><small className="hint">Erfordert 8 Katzen und 80 Ruf. Dauerhafte Produktionsboni.</small></section>}
 {tab==="garden"&&<section className="card"><h1>Besuchergarten</h1><p>Besonderes Futter und Spielzeug locken fremde Katzen an. Seltene Besucher können adoptiert werden.</p><button className="big" onClick={attract}>🍣 Premiumfutter auslegen · 15 Futter</button><div className="visitor-grid">{s.visitors.length?s.visitors.map(v=><div className="visitor" key={v.id}><PixelCat cat={{...v,name:v.name,activity:"idle",age:2.2}} mini/><b>{v.name}</b><small>{RARITIES[v.rarity]} · bleibt {v.stay}s</small><button onClick={()=>adoptVisitor(v.id)}>Adoptieren · {150*(v.rarity+1)} 🪙</button></div>):<p className="empty-state">Noch keine Besucher. Lege Futter aus und warte.</p>}</div></section>}
 {tab==="show"&&<section className="card"><h1>Katzenshows</h1><p>Trainierte, gesunde und genetisch starke Katzen erzielen höhere Wertungen.</p><div className="show-stage"><PixelCat cat={{...cat,activity:"walk"}} className="show-svg-cat"/><div className="spotlight"/><b>{cat.name} · Stärke {geneScore(cat)} · {cat.wins} Siege</b></div><button className="big" onClick={enterShow}>🏆 Antreten · 50 Münzen</button>{s.showLog.map((r,i)=><div className={`result ${r.win?"win":"loss"}`} key={i}>{r.win?"🏆":"🎗️"} {r.name}: {r.score} Punkte</div>)}</section>}
 {tab==="home"&&<section className="card"><h1>Katzenanwesen</h1>{[["kitchen","Katzenküche","Produziert Futter","🥣"],["nursery","Kinderstube","Mehr Katzenplätze","🧺"],["playroom","Spielzimmer","Münzproduktion","🧶"],["garden","Garten","Mehr Besucherchancen","🌿"],["lab","Genlabor","Forschungsproduktion","🔬"],["showhall","Showhalle","Passiver Ruf","🏆"]].map(([k,t,d,i])=><Shop key={k} icon={i} title={t} desc={d} level={s.buildings[k]} cost={Math.floor(({kitchen:120,nursery:230,lab:420,playroom:180,garden:310,showhall:600}[k])*1.75**s.buildings[k])} buy={()=>buy(k)}/>)}</section>}
 {tab==="research"&&<section className="card"><h1>Genforschung <small>🔬 {fmt(s.science)}</small></h1>{[["growth","Wachstum","Schnellere körperliche Entwicklung"],["fertility","Fruchtbarkeit","Mehr Würfe und Seltenheit"],["genes","Mutationen","Stärkere vererbte Gene"],["gestation","Nestwärme","Kürzere Brutzeit"],["training","Showtraining","Höhere Wettbewerbswertung"],["offline","Ruhemodus","Mehr Offline-Ertrag"]].map(([k,t,d])=><Shop key={k} icon="🧬" title={t} desc={d} level={s.research[k]} cost={Math.floor(25*2.05**s.research[k])} buy={()=>study(k)}/>)}</section>}
 {tab==="codex"&&<section className="card"><h1>Katzenbuch <small>{s.codex.length}/{COLORS.length*PATTERNS.length}</small></h1><p>Entdecke jede Fellfarbe und jedes Muster durch Zucht, Mutation und Besucher.</p><div className="codex-grid">{COLORS.flatMap(color=>PATTERNS.map(pattern=>{const found=s.codex.includes(`${color}-${pattern}`);const preview={name:"Vorschau",color,pattern,activity:"idle",age:2.2};return <div className={found?"found":"locked"} key={`${color}-${pattern}`}><PixelCat cat={preview} mini/><b>{found?`${color} · ${pattern}`:"???"}</b></div>}))}</div></section>}
 <footer>Produktion: {production.coins.toFixed(1)} 🪙/s · {production.food.toFixed(1)} 🥣/s · {production.science.toFixed(2)} 🔬/s</footer></main>}
function Bars({cat}){return <div className="bars"><Bar label="Hunger" value={cat.hunger}/><Bar label="Glück" value={cat.happiness}/><Bar label="Gesundheit" value={cat.health}/><Bar label="Wachstum" value={cat.growth}/></div>}
function Bar({label,value}){return <div className="barrow"><span>{label}</span><div><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div><b>{Math.floor(value)}%</b></div>}
function Shop({icon,title,desc,level,cost,buy}){return <div className="shop"><span>{icon}</span><div><b>{title} · Stufe {level}</b><small>{desc}</small></div><button onClick={buy}>{fmt(cost)} 🪙</button></div>}
createRoot(document.getElementById("root")).render(<App/>);