import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";

const NAMES=["Minka","Luna","Mochi","Nala","Simba","Pixel","Flocke","Keks","Milo","Tapsi","Nova","Chili","Suki","Pünktchen","Momo","Zora"];
const COLORS=["orange","black","white","gray","cream","calico"];
const PATTERNS=["solid","tabby","tuxedo","spots","marble","lynx"];
const RARITIES=["Gewöhnlich","Selten","Episch","Legendär","Mythisch"];
const MATING_AGE=3;
const SAVE_KEY="kitty-breeder-v4";
const ACTIVITIES={idle:"Schaut sich um",walk:"Streift durch das Zimmer",eat:"Frisst genüsslich",play:"Jagt dem Garn nach",sleep:"Schläft tief",pet:"Schnurrt glücklich"};
const baseCat=(id,name,sex,color,pattern="tabby")=>({id,name,sex,color,pattern,rarity:0,age:0,growth:0,happiness:88,hunger:90,health:100,size:.55,genes:{size:2,beauty:2,energy:2,luck:1,temper:2},parents:[],generation:1,cooldown:0,wins:0,activity:"sleep"});
const empty={coins:60,food:50,toys:5,science:0,hearts:5,lineage:0,reputation:0,selected:1,nextId:3,last:Date.now(),buildings:{kitchen:0,nursery:0,lab:0,playroom:0,garden:0,showhall:0},research:{growth:0,fertility:0,genes:0,offline:0,gestation:0,training:0},cats:[baseCat(1,"Minka","♀","orange"),baseCat(2,"Milo","♂","gray","solid")],quests:{feed:0,pet:0,breed:0,show:0},nest:null,visitors:[],codex:["orange-tabby","gray-solid"],selectedA:1,selectedB:2,showLog:[]};
const load=()=>{try{return{...structuredClone(empty),...JSON.parse(localStorage.getItem(SAVE_KEY)||"{}")}}catch{return structuredClone(empty)}};
const fmt=n=>n>=1e6?(n/1e6).toFixed(1)+"M":n>=1e3?(n/1e3).toFixed(1)+"K":Math.floor(n);
const pick=a=>a[Math.floor(Math.random()*a.length)];
const stage=c=>c.age<1?"Kätzchen":c.age<3?"Jungkatze":c.age<10?"Erwachsen":c.age<15?"Senior":"Uralte Katze";
const stageClass=c=>c.age<1?"baby":c.age<3?"young":c.age<10?"adult":c.age<15?"senior":"ancient";
const geneScore=c=>Object.values(c.genes).reduce((a,b)=>a+b,0);
const value=c=>Math.floor(geneScore(c)*18*(1+c.rarity*.65)*(1+c.generation*.12)+c.wins*55);
const keyOf=c=>`${c.color}-${c.pattern}`;
const PALETTES={orange:["#d78943","#f0ad62","#6d3b2b"],black:["#25222d","#45404f","#111019"],white:["#ddd8cf","#fffaf0","#77717b"],gray:["#696a73","#96969d","#34343c"],cream:["#d7ba83","#f0d6a3","#70563e"],calico:["#c47a46","#eee0c8","#332b32"]};

function PixelCat({cat,mini=false,className=""}){
 const p=PALETTES[cat.color]||PALETTES.orange,closed=cat.activity==="sleep"||cat.activity==="pet";
 return <svg className={`pixel-svg-cat ${mini?"mini-svg-cat":""} ${stageClass(cat)} activity-${cat.activity||"idle"} ${className}`} viewBox="0 0 32 32" role="img" aria-label={`${cat.name||"Katze"} Pixelkatze`} shapeRendering="crispEdges">
  <g className="cat-whole"><g className="cat-tail"><rect x="3" y="17" width="3" height="8" fill={p[2]}/><rect x="5" y="13" width="3" height="5" fill={p[0]}/><rect x="7" y="11" width="3" height="4" fill={p[1]}/></g>
  <g className="cat-body"><rect x="8" y="15" width="15" height="11" fill={p[0]}/><rect x="10" y="13" width="11" height="3" fill={p[1]}/><rect x="9" y="24" width="4" height="5" fill={p[2]}/><rect x="18" y="24" width="4" height="5" fill={p[2]}/></g>
  <g className="cat-head"><rect x="16" y="7" width="12" height="13" fill={p[0]}/><g className="cat-ears"><rect x="17" y="4" width="4" height="5" fill={p[2]}/><rect x="24" y="4" width="4" height="5" fill={p[2]}/></g><rect x="18" y="9" width="8" height="8" fill={p[1]}/><rect className="cat-eye cat-eye-left" x="19" y={closed?12:11} width="2" height={closed?1:2} fill="#17131d"/><rect className="cat-eye cat-eye-right" x="24" y={closed?12:11} width="2" height={closed?1:2} fill="#17131d"/><rect x="22" y="14" width="2" height="2" fill="#d98a91"/><rect className="cat-mouth" x="21" y="16" width="4" height="1" fill="#4b2730"/></g>
  {cat.pattern!=="solid"&&<g className="cat-pattern" fill={p[2]} opacity=".9"><rect x="12" y="15" width="2" height="6"/><rect x="16" y="15" width="2" height="5"/>{cat.pattern==="spots"&&<rect x="19" y="20" width="3" height="3"/>}{cat.pattern==="tuxedo"&&<rect x="20" y="15" width="4" height="7" fill="#f4eee6"/>}</g>}</g>
  {cat.activity==="sleep"&&<g className="sleep-z" fill="#f6e6ff"><text x="25" y="8" fontSize="5">Z</text><text x="28" y="4" fontSize="4">Z</text></g>}
 </svg>;
}

function App(){
 const[s,setS]=useState(load),[tab,setTab]=useState("cats"),[note,setNote]=useState("");
 const cat=s.cats.find(c=>c.id===s.selected)||s.cats[0];
 const production=useMemo(()=>{const mood=s.cats.reduce((a,c)=>a+(c.happiness+c.health)/200,0);return{coins:(s.buildings.playroom*.08+s.buildings.garden*.03+s.cats.length*.015)*mood*(1+s.lineage*.08),food:s.buildings.kitchen*.12,science:s.buildings.lab*.025,reputation:s.buildings.showhall*.004}},[s.cats,s.buildings,s.lineage]);
 const toast=t=>{setNote(t);clearTimeout(window.kt);window.kt=setTimeout(()=>setNote(""),1900)};
 const mutate=fn=>setS(p=>{const n=structuredClone(p);fn(n);return n});
 const setActivity=(id,a,ms=2400)=>{mutate(n=>{const c=n.cats.find(x=>x.id===id);if(c)c.activity=a});setTimeout(()=>mutate(n=>{const c=n.cats.find(x=>x.id===id);if(c&&c.activity===a)c.activity="idle"}),ms)};
 const act=type=>{const id=s.selected;mutate(n=>{const c=n.cats.find(x=>x.id===id);if(!c)return;if(type==="feed"){if(n.food<5)return toast("Nicht genug Futter");n.food-=5;c.hunger=Math.min(100,c.hunger+27);c.growth+=8+n.research.growth*2;n.quests.feed++}if(type==="pet"){c.happiness=Math.min(100,c.happiness+16);c.health=Math.min(100,c.health+2);n.hearts+=1+c.rarity;n.quests.pet++}if(type==="play"){if(n.toys<1)return toast("Keine Spielzeuge");n.toys--;c.happiness=Math.min(100,c.happiness+24);c.hunger=Math.max(0,c.hunger-5);c.growth+=5}if(type==="sleep"){c.health=Math.min(100,c.health+9);c.happiness=Math.min(100,c.happiness+5)}if(c.growth>=100){c.growth-=100;c.size+=.08+c.genes.size*.018;n.coins+=Math.max(2,Math.floor(6*c.size));toast(`${c.name} ist gewachsen!`)}});setActivity(id,type==="feed"?"eat":type,type==="sleep"?5000:2600)};
 const buy=kind=>mutate(n=>{const lv=n.buildings[kind],base={kitchen:160,nursery:300,lab:650,playroom:280,garden:420,showhall:900}[kind],cost=Math.floor(base*1.8**lv);if(n.coins<cost)return toast("Nicht genug Münzen");n.coins-=cost;n.buildings[kind]++;toast("Gebäude verbessert")});
 const study=kind=>mutate(n=>{const lv=n.research[kind],cost=Math.floor(35*2.15**lv);if(n.science<cost)return toast("Nicht genug Forschung");n.science-=cost;n.research[kind]++});
 const startBreed=()=>mutate(n=>{if(n.nest)return toast("Das Nest ist belegt");const a=n.cats.find(c=>c.id===n.selectedA),b=n.cats.find(c=>c.id===n.selectedB);if(!a||!b||a.id===b.id)return toast("Wähle zwei verschiedene Katzen");if(a.sex===b.sex)return toast("Du brauchst ♀ und ♂");if(a.age<MATING_AGE||b.age<MATING_AGE)return toast(`Beide Katzen müssen ${MATING_AGE} Jahre alt sein`);if(a.cooldown>0||b.cooldown>0)return toast("Eine Katze hat noch Zuchtpause");if(n.hearts<20)return toast("Du brauchst 20 Herzen");if(n.cats.length>=4+n.buildings.nursery*2)return toast("Kinderstube voll");n.hearts-=20;const duration=Math.max(20,55-n.research.gestation*5);n.nest={a:a.id,b:b.id,remaining:duration,total:duration,eggs:1+(Math.random()<.2+n.research.fertility*.035?1:0)};a.cooldown=120;b.cooldown=120});
 const hatch=()=>mutate(n=>{if(!n.nest||n.nest.remaining>0)return;const a=n.cats.find(c=>c.id===n.nest.a),b=n.cats.find(c=>c.id===n.nest.b),babies=[];for(let i=0;i<n.nest.eggs;i++){const gene=k=>Math.max(1,Math.round((a.genes[k]+b.genes[k])/2)+(Math.random()<.08+n.research.genes*.03?1:0)),pattern=Math.random()<.72?pick([a.pattern,b.pattern]):pick(PATTERNS),color=Math.random()<.72?pick([a.color,b.color]):pick(COLORS),rarity=Math.min(4,Math.max(a.rarity,b.rarity)+(Math.random()<.06+n.research.fertility*.015?1:0));const baby={...baseCat(n.nextId++,pick(NAMES),Math.random()<.5?"♀":"♂",color,pattern),rarity,parents:[a.name,b.name],generation:Math.max(a.generation,b.generation)+1,genes:{size:gene("size"),beauty:gene("beauty"),energy:gene("energy"),luck:gene("luck"),temper:gene("temper")}};babies.push(baby);if(!n.codex.includes(keyOf(baby)))n.codex.push(keyOf(baby))}n.cats.push(...babies);n.selected=babies[0].id;n.nest=null;n.quests.breed++;toast(`${babies.length} Kätzchen geboren!`)});
 const enterShow=()=>mutate(n=>{const c=n.cats.find(x=>x.id===n.selected);if(c.age<MATING_AGE)return toast(`Shows erst ab ${MATING_AGE} Jahren`);if(n.coins<50)return toast("50 Münzen benötigt");n.coins-=50;const score=geneScore(c)*10+c.happiness*.4+c.health*.4+c.rarity*40+n.research.training*12,rival=120+n.reputation+Math.random()*120,win=score>rival;if(win){const prize=Math.floor(70+score*.35);n.coins+=prize;n.reputation+=3+c.rarity;c.wins++;toast(`${c.name} gewinnt ${prize} Münzen!`)}else n.reputation+=.5;n.showLog.unshift({name:c.name,win,score:Math.floor(score)});n.showLog=n.showLog.slice(0,5)});
 const attract=()=>mutate(n=>{if(n.food<15)return toast("15 Futter benötigt");n.food-=15;const visitor={id:Date.now(),name:pick(NAMES),color:pick(COLORS),pattern:pick(PATTERNS),rarity:Math.random()<.15?1:0,stay:60};n.visitors.push(visitor)});
 const adoptVisitor=id=>mutate(n=>{const v=n.visitors.find(x=>x.id===id);if(!v)return;const cost=220*(v.rarity+1);if(n.coins<cost)return toast(`${cost} Münzen benötigt`);if(n.cats.length>=4+n.buildings.nursery*2)return toast("Kinderstube voll");n.coins-=cost;const c=baseCat(n.nextId++,v.name,Math.random()<.5?"♀":"♂",v.color,v.pattern);c.rarity=v.rarity;n.cats.push(c);n.visitors=n.visitors.filter(x=>x.id!==id)});
 const sell=()=>mutate(n=>{if(n.cats.length<=2)return toast("Zwei Katzen müssen bleiben");const c=n.cats.find(x=>x.id===n.selected);n.coins+=value(c);n.cats=n.cats.filter(x=>x.id!==c.id);n.selected=n.cats[0].id});
 const prestige=()=>mutate(n=>{if(n.reputation<80||n.cats.length<8)return toast("Benötigt 8 Katzen und 80 Ruf");const gain=Math.max(1,Math.floor((n.reputation+n.cats.reduce((a,c)=>a+c.generation*3+c.rarity*5,0))/70)),fresh=structuredClone(empty);fresh.lineage=n.lineage+gain;fresh.coins=60+gain*30;Object.assign(n,fresh)});
 useEffect(()=>{const offline=Math.min(21600,(Date.now()-(s.last||Date.now()))/1000)*(1+s.research.offline*.2);if(offline>30)mutate(n=>{n.coins+=production.coins*offline;n.food+=production.food*offline;n.science+=production.science*offline;toast(`Offline: +${fmt(production.coins*offline)} Münzen`)});const t=setInterval(()=>mutate(n=>{n.coins+=production.coins;n.food+=production.food;n.science+=production.science;n.reputation+=production.reputation;n.last=Date.now();if(n.nest)n.nest.remaining=Math.max(0,n.nest.remaining-1);n.visitors.forEach(v=>v.stay--);n.visitors=n.visitors.filter(v=>v.stay>0);n.cats.forEach(c=>{c.age+=1/900;c.cooldown=Math.max(0,c.cooldown-1);c.hunger=Math.max(0,c.hunger-.035);c.happiness=Math.max(0,c.happiness-.018);if(c.hunger<20)c.health=Math.max(0,c.health-.04);else c.health=Math.min(100,c.health+.012);if(c.activity==="idle"&&Math.random()<.018)c.activity=pick(["walk","sleep","idle"])})}),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>localStorage.setItem(SAVE_KEY,JSON.stringify({...s,last:Date.now()})),[s]);
 const adultOptions=s.cats.filter(c=>c.age>=MATING_AGE),navItems=[["cats","🐾","Hof"],["breed","💞","Zucht"],["garden","🌿","Garten"],["show","🏆","Shows"],["home","🏠","Ausbau"],["research","🧬","Forschung"],["codex","📖","Buch"]];
 return <main className="app"><div className={`toast ${note?"show":""}`}>{note}</div><header className="resource-hud"><div className="resource-main"><small>Münzen</small><strong>🪙 {fmt(s.coins)}</strong><em>+{production.coins.toFixed(2)}/s</em></div><div className="resource-chip"><span>🥣</span><b>{fmt(s.food)}</b><small>Futter</small></div><div className="resource-chip"><span>💗</span><b>{fmt(s.hearts)}</b><small>Herzen</small></div><div className="resource-chip"><span>🏆</span><b>{fmt(s.reputation)}</b><small>Ruf</small></div><div className="resource-chip"><span>🧬</span><b>{s.lineage}</b><small>Linie</small></div></header>
 <nav className="mobile-nav">{navItems.map(([k,i,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}><span>{i}</span><small>{l}</small></button>)}</nav>
 {tab==="cats"&&<><section className="card hero"><div className="title"><div><h1>{cat.name} <span>{cat.sex}</span></h1><p>{RARITIES[cat.rarity]} · Gen. {cat.generation} · {stage(cat)}</p></div><b className={`rarity r${cat.rarity}`}>{"★".repeat(cat.rarity+1)}</b></div><div className={`scene scene-${cat.activity}`}><div className="pixel-room"/><div className="food-bowl"/><div className="yarn-ball"/><PixelCat cat={cat}/><div className="activity-bubble">{ACTIVITIES[cat.activity]}</div><span className="age">{cat.age.toFixed(1)} J. · {cat.age<MATING_AGE?`zuchtreif in ${(MATING_AGE-cat.age).toFixed(1)} J.`:"zuchtreif"}</span></div><Bars cat={cat}/><div className="actions"><button onClick={()=>act("feed")}>🥣<small>Füttern</small></button><button onClick={()=>act("pet")}>💗<small>Kuscheln</small></button><button onClick={()=>act("play")}>🧶<small>Spielen</small></button><button onClick={()=>act("sleep")}>🌙<small>Schlafen</small></button><button onClick={enterShow}>🏆<small>Show</small></button><button className="danger" onClick={sell}>🏠<small>Vermitteln</small></button></div></section><section className="card"><h2>Deine Katzen <small>{s.cats.length}/{4+s.buildings.nursery*2}</small></h2><div className="catgrid">{s.cats.map(c=><button key={c.id} className={`catcard ${c.id===s.selected?"selected":""}`} onClick={()=>setS(p=>({...p,selected:c.id}))}><PixelCat cat={c} mini/><b>{c.name}</b><small>{c.age.toFixed(1)} J. · {stage(c)}</small></button>)}</div></section></>}
 {tab==="breed"&&<section className="card"><h1>Zuchtzentrum</h1><p>Katzen können sich erst ab <b>{MATING_AGE} Jahren</b> paaren. Bis dahin müssen sie gepflegt und großgezogen werden.</p>{adultOptions.length<2&&<div className="locked-note">🔒 Noch nicht genügend zuchtreife Katzen. Deine Katzen altern auch offline.</div>}<div className="parent-pickers"><label>Mutter<select value={s.selectedA} onChange={e=>setS(p=>({...p,selectedA:+e.target.value}))}>{adultOptions.map(c=><option key={c.id} value={c.id}>{c.name} {c.sex} · {c.age.toFixed(1)} J.</option>)}</select></label><label>Vater<select value={s.selectedB} onChange={e=>setS(p=>({...p,selectedB:+e.target.value}))}>{adultOptions.map(c=><option key={c.id} value={c.id}>{c.name} {c.sex} · {c.age.toFixed(1)} J.</option>)}</select></label></div>{s.nest?<div className="nest"><div className="nest-eggs">{"🥚".repeat(s.nest.eggs)}</div><b>{s.nest.remaining>0?`Geburt in ${Math.ceil(s.nest.remaining)} Sekunden`:"Die Kätzchen sind bereit!"}</b><div className="progress"><i style={{width:`${100-s.nest.remaining/s.nest.total*100}%`}}/></div><button className="big" disabled={s.nest.remaining>0} onClick={hatch}>🐾 Kätzchen zur Welt bringen</button></div>:<button className="big" disabled={adultOptions.length<2} onClick={startBreed}>💞 Zucht beginnen · 20 Herzen</button>}<button className="prestige" onClick={prestige}>🧬 Neue Blutlinie beginnen</button></section>}
 {tab==="garden"&&<section className="card"><h1>Besuchergarten</h1><button className="big" onClick={attract}>🍣 Premiumfutter auslegen · 15 Futter</button><div className="visitor-grid">{s.visitors.length?s.visitors.map(v=><div className="visitor" key={v.id}><PixelCat cat={{...v,activity:"idle",age:0}} mini/><b>{v.name}</b><small>{RARITIES[v.rarity]} · {v.stay}s</small><button onClick={()=>adoptVisitor(v.id)}>Adoptieren · {220*(v.rarity+1)} 🪙</button></div>):<p className="empty-state">Noch keine Besucher.</p>}</div></section>}
 {tab==="show"&&<section className="card"><h1>Katzenshows</h1><div className="show-stage"><PixelCat cat={{...cat,activity:"walk"}} className="show-svg-cat"/><div className="spotlight"/><b>{cat.name} · {cat.wins} Siege</b></div><button className="big" disabled={cat.age<MATING_AGE} onClick={enterShow}>🏆 Antreten · 50 Münzen</button>{s.showLog.map((r,i)=><div className={`result ${r.win?"win":"loss"}`} key={i}>{r.win?"🏆":"🎗️"} {r.name}: {r.score}</div>)}</section>}
 {tab==="home"&&<section className="card"><h1>Katzenanwesen</h1>{[["kitchen","Katzenküche","Produziert langsam Futter","🥣"],["nursery","Kinderstube","Mehr Katzenplätze","🧺"],["playroom","Spielzimmer","Langsame Münzproduktion","🧶"],["garden","Garten","Besucher und kleine Erträge","🌿"],["lab","Genlabor","Forschungsproduktion","🔬"],["showhall","Showhalle","Passiver Ruf","🏆"]].map(([k,t,d,i])=><Shop key={k} icon={i} title={t} desc={d} level={s.buildings[k]} cost={Math.floor(({kitchen:160,nursery:300,lab:650,playroom:280,garden:420,showhall:900}[k])*1.8**s.buildings[k])} buy={()=>buy(k)}/>)}</section>}
 {tab==="research"&&<section className="card"><h1>Genforschung <small>🔬 {fmt(s.science)}</small></h1>{[["growth","Wachstum","Mehr Wachstum durch Pflege"],["fertility","Fruchtbarkeit","Bessere Würfe"],["genes","Mutationen","Stärkere Gene"],["gestation","Nestwärme","Kürzere Wartezeit"],["training","Showtraining","Höhere Wertung"],["offline","Ruhemodus","Mehr Offline-Ertrag"]].map(([k,t,d])=><Shop key={k} icon="🧬" title={t} desc={d} level={s.research[k]} cost={Math.floor(35*2.15**s.research[k])} buy={()=>study(k)}/>)}</section>}
 {tab==="codex"&&<section className="card"><h1>Katzenbuch <small>{s.codex.length}/{COLORS.length*PATTERNS.length}</small></h1><div className="codex-grid">{COLORS.flatMap(color=>PATTERNS.map(pattern=>{const found=s.codex.includes(`${color}-${pattern}`),preview={name:"Vorschau",color,pattern,activity:"idle",age:0};return <div className={found?"found":"locked"} key={`${color}-${pattern}`}><PixelCat cat={preview} mini/><b>{found?`${color} · ${pattern}`:"???"}</b></div>}))}</div></section>}
 <footer>Langsamer Modus · {production.coins.toFixed(2)} 🪙/s · Zuchtreife ab {MATING_AGE} Jahren</footer></main>;
}
function Bars({cat}){return <div className="bars"><Bar label="Hunger" value={cat.hunger}/><Bar label="Glück" value={cat.happiness}/><Bar label="Gesundheit" value={cat.health}/><Bar label="Wachstum" value={cat.growth}/></div>}
function Bar({label,value}){return <div className="barrow"><span>{label}</span><div><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div><b>{Math.floor(value)}%</b></div>}
function Shop({icon,title,desc,level,cost,buy}){return <div className="shop"><span>{icon}</span><div><b>{title} · Stufe {level}</b><small>{desc}</small></div><button onClick={buy}>{fmt(cost)} 🪙</button></div>}
createRoot(document.getElementById("root")).render(<App/>);